# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 2.2.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input


# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#Build Relase instead of Debug
configuration: Release

artifacts:
  - path: '**\Tulpep.ActiveDirectoryObjectPicker*.nupkg'
    name: Tulpep.ActiveDirectoryObjectPicker.nupkg

after_test:
  - ps: .\Nuget\build.ps1

#Publish NuGet
deploy:
  provider: NuGet
  api_key:
    secure: WALEGnw+g6U2njECiTL7xg47/rbkW5V2iwrFNV+XBTRGUdbGnx1CPgVTbBPPiQ93
  artifact: /.*\.nupkg/
  on:
    branch: master
