# http://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2019

# version format
version: 3.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input


# Assembly Info
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'

#Build Relase instead of Debug
configuration: Release

# Make sure all NuGet packages are installed before building.
before_build:
  - nuget restore

artifacts:
  - path: '**\Tulpep.ActiveDirectoryObjectPicker*.nupkg'
    name: Tulpep.ActiveDirectoryObjectPicker.nupkg

#Publish NuGet
deploy:
  provider: NuGet
  api_key:
    secure: +Xu610YAOninQxlJRcuTB8nSoP9rh5Ftbm8RyJ9PELNLVj2Z737hV26cS1Xi1J8v
  artifact: /.*\.nupkg/
  on:
    branch: master
