# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 0.1.{build}-alpha

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input


# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#Build Relase instead of Debug
configuration: Release

artifacts:
  - path: CubicOrange.Windows.Forms.ActiveDirectory\bin\Release\CubicOrange.Windows.Forms.ActiveDirectory.dll
    name: ActiveDirectory.dll
  - path: '**\*.nupkg'
    name: ActiveDirectory.nupkg

after_test:
  - ps: .\Nuget\build.ps1

#Publish NuGet
deploy:
  provider: NuGet
  api_key:
    secure: iMjHg2GzZQKygPbCUobQ3V1cUSO+Bxiyk0S6941I5xEe1/bLNdHAn8A7cUbwM9kT
    artifact: /.*\.nupkg/
